language: rust
rust:
  - 1.1.0
  - 1.2.0
  - 1.3.0
  - beta
  - nightly
  - stable
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose --features ci
  - cargo doc
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  echo '<meta http-equiv=refresh content=0;url=semver/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
language: rust
env:
  global:
    secure: "I6tYuqMZ/NQ/lt+vl9rZutkoyG+AhTtIGloqNm8JIbrSHFSe/S4+Wou3z/BKR89k2OrkwOJnhTCeAu3kK+HGPkf5/iryI0JctelVYRLWxvUCSIyuc5fcBuCyikIeW8OnT9myE9QP7ZFBPo7s2uEboWKZC11A2Ub/ZdY303gBQTU="
notifications:
  email:
    on_success: never
