[package]

name = "semver"
version = "0.4.1"
authors = ["Steve Klabnik <steve@steveklabnik.com>", "The Rust Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/steveklabnik/semver"
homepage = "https://docs.rs/crate/semver/"
documentation = "https://docs.rs/crate/semver/^0.4.0"
description = """
Semantic version parsing and comparison.
"""

[dependencies]
semver-parser = "0.6.1"

[features]
default = []

# are we testing on CI?
ci = []

[dev-dependencies]
crates-index = "0.4.0"
tempdir = "0.3.4"
